//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDRTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacion
    {
        public string Id_Autorizacion { get; set; }
        public int Autorizacion_Codigo { get; set; }
        public int Id_Extension { get; set; }
    
        public virtual Extension Extensione { get; set; }
    }
}
